version: '3.3'

services:
  messages-master:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    container_name: messages-mysql-master
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: otus
      MYSQL_USER: otus
      MYSQL_PASSWORD: otus
      MYSQL_ROOT_PASSWORD: 'otus'
    ports:
      - 3446:3306
    volumes:
      - messages-mysql-master-db:/var/lib/mysql

  shard0:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql-shard0
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: otus
      MYSQL_USER: otus
      MYSQL_PASSWORD: otus
      MYSQL_ROOT_PASSWORD: 'otus'
    ports:
      - 3440:3306
    volumes:
      - mysql-shard0:/var/lib/mysql

  shard1:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql-shard1
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: otus
      MYSQL_USER: otus
      MYSQL_PASSWORD: otus
      MYSQL_ROOT_PASSWORD: 'otus'
    ports:
      - 3441:3306
    volumes:
      - mysql-shard1:/var/lib/mysql

  prometheus:
    network_mode: host
    build:
      context: prometheus
      dockerfile: Dockerfile
    container_name: prometheus
    ports:
      - 9090:9090
    command:
      - --config.file=/etc/prometheus/prometheus.yml

  grafana:
    network_mode: host
    image: grafana/grafana:latest
    volumes:
      - grafana_data:/var/lib/grafana
    ports:
      - 3000:3000

  zabbix-mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    container_name: zabbix-mysql
    restart: unless-stopped
    environment:
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix
      MYSQL_ROOT_PASSWORD: 'zabbix'
    ports:
      - 3116:3306
    volumes:
      - zabbix-mysql-data1:/var/lib/mysql

  zabbix-server:
    restart: always
    image: zabbix/zabbix-server-mysql:latest
    ports:
      - 10050:10050
      - 10051:10051
    environment:
      DB_SERVER_HOST: zabbix-mysql
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix
      MYSQL_ROOT_PASSWORD: 'zabbix'
    depends_on:
      - zabbix-mysql


  zabbix-web:
    image: zabbix/zabbix-web-apache-mysql:latest
    container_name: zabbix-web
    environment:
      DB_SERVER_HOST: zabbix-mysql
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix
      MYSQL_ROOT_PASSWORD: 'zabbix'
      ZBX_SERVER_HOST: zabbix-server
      PHP_TZ: UTC
    ports:
      - '8899:8080'
      - '443:443'
    links:
      - zabbix-mysql
      - zabbix-server
    depends_on:
      - zabbix-mysql
      - zabbix-server

volumes:
  messages-mysql-master-db:
  mysql-shard0:
  mysql-shard1:
  grafana_data:
  zabbix-mysql-data1:


