version: '3.3'

services:
  auth-master:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    container_name: auth-mysql-master
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: otus
      MYSQL_USER: otus
      MYSQL_PASSWORD: otus
      MYSQL_ROOT_PASSWORD: 'otus'
    ports:
      - 3996:3306
    volumes:
      - auth-mysql-master-db:/var/lib/mysql



volumes:
  auth-mysql-master-db:



