export const SHOW_MESSAGE = 'SHOW_MESSAGE';
export const HIDE_MESSAGE = 'HIDE_MESSAGE';

export const SHOW_LOADER = 'SHOW_LOADER';
export const HIDE_LOADER = 'HIDE_LOADER';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';

export const GET_USER_DATA = 'GET_USER_DATA';

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILED = 'REGISTER_FAILED';

export const LOGOUT = 'LOGOUT';

export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';

export const ADD_HOBBY_SUCCESS = 'ADD_HOBBY';
export const DELETE_HOBBY_SUCCESS = 'DELETE_HOBBY';


export const GET_USERS = 'GET_USERS';
export const CLEAR_USERS = 'CLEAR_USERS';
export const CLEAR_USER = 'CLEAR_USER';

export const DELETE_FRIENDSHIP = 'DELETE_FRIENDSHIP';
export const ADD_FRIEND_REQUEST = 'ADD_FRIEND_REQUEST';
export const DELETE_FRIEND_REQUEST = 'DELETE_FRIEND_REQUEST';
export const ACCEPT_FRIEND_REQUEST = 'ACCEPT_FRIEND_REQUEST';
export const DECLINE_FRIEND_REQUEST = 'DECLINE_FRIEND_REQUEST';

export const GET_FRIEND_REQUEST_USERS = 'GET_FRIEND_REQUEST_USERS';

export const GET_MESSAGES = 'GET_MESSAGES';
export const CLEAR_MESSAGES = 'CLEAR_MESSAGES';

export const GET_CHAT_USER = 'GET_CHAT_USER';
export const CLEAR_CHAT_USER = 'CLEAR_CHAT_USER';

export const ADD_NEW = 'ADD_NEW';
export const GET_NEWS = 'GET_NEWS';
export const CLEAR_NEWS = 'CLEAR_NEWS';
